#!/usr/bin/env python3
"""
img2lvgl.py - Convert an image to an LVGL 1-bit (INDEXED_1BIT) C descriptor
for the nice!view (Sharp LS0xx, 144x168, monochrome) on the beekeeb Toucan.

The output matches the format already used in this shield (see assets/images.c
and widgets/sleep.c): a 2-colour palette followed by 1bpp, MSB-first, with each
row padded to a whole byte. Index 0 = black (background), index 1 = white
(foreground / LVGL_FOREGROUND).

Usage:
    python3 img2lvgl.py LOGO.png logo            # keep native size
    python3 img2lvgl.py LOGO.png logo -W 96 -H 96 # resize (fit, keep aspect)
    python3 img2lvgl.py LOGO.png logo --dither    # Floyd-Steinberg instead of threshold
    python3 img2lvgl.py LOGO.png logo -t 160      # threshold 0-255 (default 128)
    python3 img2lvgl.py LOGO.png logo --invert    # swap black/white
    python3 img2lvgl.py LOGO.png logo > logo.c    # write to a file

Display canvas is 144 (W) x 168 (H). Keep images within that.
"""
import argparse
import sys
from PIL import Image, ImageOps


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="source image (png/jpg/bmp/...)")
    ap.add_argument("name", help="C symbol name (e.g. logo -> logo / logo_map)")
    ap.add_argument("-W", "--width", type=int, default=0, help="resize width (0 = native)")
    ap.add_argument("-H", "--height", type=int, default=0, help="resize height (0 = native)")
    ap.add_argument("-t", "--threshold", type=int, default=128, help="0-255 threshold (default 128)")
    ap.add_argument("--dither", action="store_true", help="Floyd-Steinberg dither instead of threshold")
    ap.add_argument("--invert", action="store_true", help="swap foreground/background")
    args = ap.parse_args()

    img = Image.open(args.input)
    # Flatten transparency onto black so transparent areas read as background.
    if img.mode in ("RGBA", "LA", "P"):
        img = img.convert("RGBA")
        bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
        img = Image.alpha_composite(bg, img)
    img = img.convert("L")  # grayscale

    if args.width or args.height:
        w = args.width or img.width
        h = args.height or img.height
        img = ImageOps.contain(img, (w, h))  # fit, preserve aspect

    w, h = img.width, img.height

    if args.dither:
        bw = img.convert("1")  # Floyd-Steinberg
    else:
        bw = img.point(lambda p: 255 if p >= args.threshold else 0, mode="1")

    px = bw.load()
    # In Pillow mode "1": 255 = white. We map white -> index 1 (foreground).
    def fg(x, y):
        on = px[x, y] != 0
        return (not on) if args.invert else on

    stride = (w + 7) // 8  # bytes per row, byte-aligned
    rows = []
    for y in range(h):
        row = bytearray(stride)
        for x in range(w):
            if fg(x, y):
                row[x >> 3] |= 0x80 >> (x & 7)  # MSB-first
        rows.append(row)

    data_size = 8 + stride * h  # 8 palette bytes + bitmap
    name = args.name

    out = []
    out.append("// Generated by img2lvgl.py -- nice!view 1-bit (INDEXED_1BIT)")
    out.append(f"// source: {args.input}  size: {w}x{h}")
    out.append("#include <lvgl.h>")
    out.append("")
    out.append(f"#ifndef LV_ATTRIBUTE_IMG_{name.upper()}")
    out.append(f"#define LV_ATTRIBUTE_IMG_{name.upper()}")
    out.append("#endif")
    out.append("")
    out.append("const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
               f"LV_ATTRIBUTE_IMG_{name.upper()} uint8_t {name}_map[] = {{")
    out.append("    0x00, 0x00, 0x00, 0xff, /*Color of index 0 - black*/")
    out.append("    0xff, 0xff, 0xff, 0xff, /*Color of index 1 - white*/")
    for y, row in enumerate(rows):
        line = ", ".join(f"0x{b:02x}" for b in row)
        out.append(f"    {line},")
    out.append("};")
    out.append("")
    out.append(f"const lv_img_dsc_t {name} = {{")
    out.append("    .header.cf = LV_IMG_CF_INDEXED_1BIT,")
    out.append("    .header.always_zero = 0,")
    out.append("    .header.reserved = 0,")
    out.append(f"    .header.w = {w},")
    out.append(f"    .header.h = {h},")
    out.append(f"    .data_size = {data_size},")
    out.append(f"    .data = {name}_map,")
    out.append("};")
    out.append("")
    print("\n".join(out))
    sys.stderr.write(f"[img2lvgl] {name}: {w}x{h}, stride {stride}B, data_size {data_size}B\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
